### PR TITLE
Setup Database Schema

### PR DESCRIPTION
**Pull request by qusai122**
### In this Branch
**I created the following models**

- Brand model
- Category model
- Colors model
- Product model 
- Address model 
- Cart model 
- Favorites List model 
- User Payment model 
- User model
- Order model 
- Variants model 
- Variant options model 

**Things need to be done**
- [ ] add validations
- [ ] Rating model 

you can find the properties in the following diagram
[lucid diagram](https://lucid.app/lucidchart/ea3a4dbc-33f1-4cde-aab4-34947b0cd696/edit?viewport_loc=-452%2C425%2C1184%2C619%2C0_0&invitationId=inv_5f5651ce-92e1-49da-8d92-96db4cfa9909)

### CODE REVIEW

**Review by mshareef-kiitos — CHANGES_REQUESTED** [review]
Thanks for the hard work.
Could you draw it on a tool like draw.io so it makes it easier to check the schema?

**Comment by qusai122** [comment]
@mshareef-kiitos 

you can find the properties in the following diagram
[lucid diagram](https://lucid.app/lucidchart/ea3a4dbc-33f1-4cde-aab4-34947b0cd696/edit?viewport_loc=-452%2C425%2C1184%2C619%2C0_0&invitationId=inv_5f5651ce-92e1-49da-8d92-96db4cfa9909)

you may need to login with an account, but you have the access using the link.

**Review by mshareef-kiitos — CHANGES_REQUESTED** [review]
Thanks for the hard work, these are my comments:
- Remove the ratings table, it will be a static data in the frontend.
- Use one case-style for table names, so change the `User` to `user`.
- No need to store the payments, it will be stored at the tool we are going to use at frontend (Stripe).
- There should be relation between `order` and `cart`, and no need for the relation between  `order` and `products`. Also, you will need to change the relation between `cart` and `product` to many-to-many relationship (in the mid-table, add the quantity and price).
- Add the order fields (quick suggestion: status, cart_id, email). The email should be saved because not all orders has a user, there's some checkouts that could happen without any user.
- The product could have multiple variants, not only colors, so the right way to do it is to create a variants table with a many-to-many relationship with the products (in the mid-table, add the values for that varient, ex: for colors: `blue`, `green`, ...).

Thanks!

**Review by mAbadsa — APPROVED** [review]

**Comment by qusai122** [comment]
@mshareef-kiitos Hello mo, thanks for the great review

- Remove the ratings
- Remove the payments
- Fix relations
- Add required fields to the order
- Create variant tables

**Use one case-style:** We already did that for the table names, the User is the model "Class" so it has to start with a capital letter

**Review by mshareef-kiitos — CHANGES_REQUESTED** [review]
have some comments after the updates:
- No need for the `product_id` or `order_id` in the `carts` table
- Add `product_id` and `cart_id` in the table of `cart_item`
- `orders` table should have a `user_id` and `cart_id`.
- This is not the best way to implement variants table, better way is to create the following tables:
  - `variants` table : contains `name` and `options`
  - `product_variants` table: contains `product_id`, `variant_id`, and `available_options`
- In `users` table, no need for the fields: `favorites_list`, `addresses`, `ratings`, `orders`, `user_payments`.
- In users table, change the `cart_id` to `current_cart_id`, which will present the user's current cart id.

**Pull request merged**
